version: '3.8'

services:
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - landingPage
      - flexbackend
      
  landingPage:
    container_name: landingPage
    image: landingpage
    build:
      context: landingPage
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - flexbackend
    
  flexbackend:
    container_name: flexbackend
    image: flexbackend
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4500:4500"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres     
  db:
    container_name: db
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}