version: '3.8'

services:
  flex.backend:
    container_name: flex.backend
    image: backend
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4500:4500"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db2:5432/postgres     
  db:
    container_name: db
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}